version: "3"
networks:
  vpc:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

services:
  app-blue:
    hostname: app-blue
    image: jinseongwon/community_feed:latest
    ports:
      - 8080
    volumes:
      - ./src/main/resources/application-blue.yml:/application.yml
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      vpc:
        ipv4_address: 192.168.0.3

  app-green:
    hostname: app-green
    image: jinseongwon/community_feed:latest
    ports:
      - 8080
    volumes:
      - ./src/main/resources/application-green.yml:/application.yml
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      vpc:
        ipv4_address: 192.168.0.4

  api-gateway:
    image: nginx
    hostname: api-gateway
    privileged: true
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/*.conf:/etc/nginx/conf.d/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    #      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      vpc:
        ipv4_address: 192.168.0.2
    user: root
    depends_on:
      - app-blue
      - app-green