version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ${HOST_JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

  worker-1:
    image: jenkins/ssh-agent:jdk17
    volumes:
      - ${HOST_JENKINS_WORKER_1}:/home/jenkins
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqDo8LPWYyMzoCXFBVFO93EHqLoNOxxcPO/r3loYtXNS2ept/iCSGOc30AYcYj8PZRljF9GNfXM6hZH220oaJtpDn0BXn1JdvvLYaZ0CDDPce179Bfc25riIgAbzRXB2s76zEHyFz7J+jWCfXQQ0pS7VQDXpEAozKcFFz4O8HXFUGKk3R/gyN9Vv+GXLKE93KMDOWPRLccyJtPLVwK3g5VLzYTM4jz9LthwFrywwKqobL6Ezoip13jBbRWE48JocNWOY49L4wS9gUYg9WnqLJQun5g6qGN/SMPjv/MA2hnLVXnoV4COjSpZ3pkrIHmfFWsbqrvOwsdSdfFI2B1yBXoYGhYWLJzEjiufyQMQdAo17DMIuyQ6Dub8pgitOTlvgmtl1raCRzvVQGNz78mnPzCiRQnrULI83yw7lXbAFURqSdxYHznhUDtm0D1NiRDSUUwoEv9z7ZdR/BJoC9oDYU4gk0AlBurVMw+ZmAirFSh4ZgrrIilQHJvAX4oJpRqlcs=
    networks:
      - jenkins_network

  sonarqube:
    image: sonarqube:9-community
    ports:
      - "9000:9000"
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge
