spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community_feed
    username: root
    password: 1234

  # Console log color 설정
  output:
    ansi:
      enabled: always

  # thymeleaf 경로 지정
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/

  jpa:
    show-sql: true        #sql 문 출력
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  #sql문을 라인에 맞게 출력
    open-in-view: false   #DB와 application 와 연결 스레드 관리 (기본값 : true)

#비밀키
secret-key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9

#Firebase 인증서 파일 (json 파일) 읽어오기
fcm :
  certification : community-service-adminsdk.json   # 파일명

